In [1]:
from footbot.data import element_data

In [2]:
element_data.get_element_df()

,element,current_event,datetime,safe_web_name,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,...,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
0,1,4,2019-09-08 05:20:38.403236,mustafi,0,0,0,NaN,NaN,0,...,0.0,0,4156,408,21627,1845,0.0,0.0,Mustafi,0
1,2,4,2019-09-08 05:20:38.403236,bellerin,0,0,0,0.0,0.0,0,...,0.0,0,827,176,4558,470,0.0,0.0,Beller√≠n,0
2,3,4,2019-09-08 05:20:38.403236,kolasinac,0,0,17,100.0,100.0,0,...,13.0,2,8025,4859,54232,3237,0.1,0.4,Kolasinac,0
3,4,4,2019-09-08 05:20:38.403236,maitland-niles,1,3,81,NaN,NaN,1,...,19.0,16,379902,44221,156189,25760,0.8,3.1,Maitland-Niles,0
4,5,4,2019-09-08 05:20:38.403236,sokratis,0,2,73,NaN,NaN,1,...,2.0,11,49251,10332,47579,9182,0.6,2.2,Sokratis,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,419,4,2019-09-08 05:20:38.403236,cavaleiro,0,0,0,0.0,0.0,0,...,0.0,0,159,31,459,52,0.0,0.0,Cavaleiro,0
528,420,4,2019-09-08 05:20:38.403236,dendoncker,0,0,30,100.0,75.0,1,...,35.0,8,254802,16676,349350,62883,0.4,1.8,Dendoncker,0
529,473,4,2019-09-08 05:20:38.403236,vallejo,0,0,0,NaN,NaN,0,...,0.0,0,2205,437,12236,1414,0.0,0.0,Vallejo,0
530,487,4,2019-09-08 05:20:38.403236,cutrone,0,0,3,NaN,NaN,0,...,38.0,4,11120,1552,57500,5373,0.2,0.7,Cutrone,0
531,528,4,2019-09-08 05:20:38.403236,neto,0,0,3,NaN,NaN,0,...,8.0,2,1650,276,1041,327,0.1,0.4,Neto,1