In [1]:
from footbot.data import element_data

In [3]:
element_df = element_data.get_element_df()
element_df.head()

,element,current_event,datetime,safe_web_name,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,...,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
0,1,4,2019-09-08 06:26:56.133776,mustafi,0,0,0,NaN,NaN,0,...,0.0,0,4156,408,21627,1845,0.0,0.0,Mustafi,0
1,2,4,2019-09-08 06:26:56.133776,bellerin,0,0,0,0.0,0.0,0,...,0.0,0,827,176,4558,470,0.0,0.0,Bellerín,0
2,3,4,2019-09-08 06:26:56.133776,kolasinac,0,0,17,100.0,100.0,0,...,13.0,2,8027,4861,54236,3241,0.1,0.4,Kolasinac,0
3,4,4,2019-09-08 06:26:56.133776,maitland-niles,1,3,81,NaN,NaN,1,...,19.0,16,379920,44239,156209,25780,0.8,3.1,Maitland-Niles,0
4,5,4,2019-09-08 06:26:56.133776,sokratis,0,2,73,NaN,NaN,1,...,2.0,11,49253,10334,47584,9187,0.6,2.2,Sokratis,1

In [5]:
list(element_df.columns)

['element',
 'current_event',
 'datetime',
 'safe_web_name',
 'assists',
 'bonus',
 'bps',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'clean_sheets',
 'code',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'creativity',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'first_name',
 'form',
 'goals_conceded',
 'goals_scored',
 'ict_index',
 'in_dreamteam',
 'influence',
 'minutes',
 'news',
 'news_added',
 'now_cost',
 'own_goals',
 'penalties_missed',
 'penalties_saved',
 'photo',
 'points_per_game',
 'red_cards',
 'saves',
 'second_name',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team',
 'team_code',
 'threat',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'yellow_cards']

In [22]:
element_df.groupby('status').size()

# a - active
# d - danger of injury
# i - injured
# n - on loan out of league
# s - suspended
# u - transferred out of league

status
a    396
d     33
i     46
n     33
s      3
u     21
dtype: int64

In [23]:
element_df[element_df['status'].isin(['a', 'd', 'i'])][[
    'safe_web_name',
    'status',
    'chance_of_playing_this_round',
    'chance_of_playing_next_round'
]].head(10)

,safe_web_name,status,chance_of_playing_this_round,chance_of_playing_next_round
0,mustafi,a,NaN,NaN
1,bellerin,i,0.0,0.0
2,kolasinac,a,100.0,100.0
3,maitland-niles,a,NaN,NaN
4,sokratis,a,NaN,NaN
7,mavropanos,i,0.0,0.0
9,holding,i,0.0,0.0
10,aubameyang,a,NaN,NaN
11,lacazette,d,100.0,75.0
13,leno,a,NaN,NaN

In [27]:
element_df.to_csv('./csvs/element_data_20190908063911', index=False)