# Set up

In [2]:
# update path with data dir
import sys
sys.path.append('../data/')
sys.path.append('../modelling/')

In [3]:
import player_data as player
import pandas as pd
import knapsack

/home/tom/footbot/venv/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

# Toy example

In [16]:
size = [21, 11, 15, 9, 34, 25, 41, 52]
weight = [22, 12, 16, 10, 35, 26, 42, 53]
capacity = 100

In [17]:
knapsack.knapsack(size, weight).solve(capacity)

(105, [0, 1, 3, 4, 5])

# Player data

In [5]:
player.get_element_df(['id', 'now_cost', 'web_name', 'team'])

      id  now_cost  team        web_name   safe_web_name
0      1        47     1            Cech            cech
1      2        49     1            Leno            leno
2      3        54     1       Koscielny       koscielny
3      4        53     1        Bellerín        bellerin
4      5        54     1         Monreal         monreal
5      6        43     1         Holding         holding
6      7        54     1         Mustafi         mustafi
7      8        50     1       Kolasinac       kolasinac
8     10        47     1      Mavropanos      mavropanos
9     11        45     1    Lichtsteiner    lichtsteiner
10    12        51     1        Sokratis        sokratis
11    13        79     1            Özil            ozil
12    14        71     1          Ramsey          ramsey
13    15        54     1           Iwobi           iwobi
14    16        42     1          Elneny          elneny
15    17        52     1           Xhaka           xhaka
16    18        68     1      Mkhitaryan      mkhitaryan
17    19        44     1          Nelson          nelson
18    20        44     1  Maitland-Niles  maitland-niles
19    21        64     1         Welbeck         welbeck
20    22        94     1       Lacazette       lacazette
21    23       109     1      Aubameyang      aubameyang
22   450        47     1        Torreira        torreira
23   451        44     1       Guendouzi       guendouzi
24   542        40     1        Martínez        martinez
25   545        45     1      Smith-Rowe      smith-rowe
26   546        40     1          Medley          medley
27   552        50     1         Nketiah         nketiah
28   563        45     1            Saka            saka
29   566        45     1         Willock         willock
..   ...       ...   ...             ...             ...
579  605        40    19         Johnson         johnson
580  421        42    20           Ruddy           ruddy
581  422        39    20          Norris          norris
582  423        47    20            Boly            boly
583  424        50    20         Douglas         douglas
584  425        53    20         Doherty         doherty
585  426        42    20           Saïss           saiss
586  427        41    20         Bennett         bennett
587  428        40    20           Batth           batth
588  429        40    20         Miranda         miranda
589  430        45    20           Coady           coady
590  431        43    20         Vinagre         vinagre
591  432        61    20            Jota            jota
592  433        49    20           Neves           neves
593  434        52    20       Cavaleiro       cavaleiro
594  435        46    20           Costa           costa
595  436        43    20      Enobakhare      enobakhare
596  437        68    20         Jiménez         jimenez
597  438        46    20        Bonatini        bonatini
598  448        43    20     Gibbs-White     gibbs-white
599  449        45    20             Mir             mir
600  454        45    20        Patrício        patricio
601  475        52    20        Moutinho        moutinho
602  483        43    20           Jonny           jonny
603  500        51    20          Traoré          traore
604  519        43    20      Dendoncker      dendoncker
605  525        40    20           Hause           hause
606  555        45    20           Giles           giles
607  567        40    20          Kilman          kilman
608  596        40    20            John            john

[609 rows x 5 columns]